### ISSUE TITLE
how do I convert these to PDF?

### ISSUE THREAD

**Issue by greenm01** [djberg96/Space-Empires-Imperium#1]

**Comment by djberg96** [comment]
If you mean the .tex files, you'll need a program called `pdflatex`. You can read more about it at https://www.tug.org/applications/pdftex/. There's different ways to install it depending on which OS you're using.

If you mean the svg/png files, you can typically do that through your favorite image editor. If you're a command line person, you can install a program called "imagemagick" and use the "convert" program.

**Comment by greenm01** [comment]
I'm using pdftex on Linux. I'm getting a bunch of  "Undefined control sequence" errors when I try to output a PDF,

pdftex -output-format=pdf main.tex

Then I'm in extended mode and I see this:

`This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian) (preloaded format=pdftex)
 restricted \write18 enabled.
entering extended mode
(./main.tex
! Undefined control sequence.
l.1 \documentclass
                  [a4paper,11pt,twocolumn]{article}`

When I hit 'R' I get a get a list of undefined control sequences

**Comment by djberg96** [comment]
Huh, strange. I'm running mactex locally and, other than a few warnings about underfull hbox's, it worked fine. I ran `pdflatex --jobname=Space_Empires_Imperium main.tex`. You could also try a program like TexStudio (that's what I normally use for an editor) and select "Tools -> Build & View".

**Comment by djberg96** [comment]
If you're still having problems, I'll just push up a PDF.

**Comment by djberg96** [comment]
I should also mention that right now I have nothing more than a standalone variant for Imperium, plus the cards. There's no actual "Space Empires 4x" integration/crossover yet. Work in progress. :)

**Comment by greenm01** [comment]
Thanks, that last command worked under MikTex on Windowz, but I had to manually install a bunch of missing packages.

Seemed more difficult than it needs to be. Please include compiled PDFs in the repo :-)

I have a copy of Space Empires 4X and looking to find the user manual for Imperium somewhere. The complete games listed on eBay are quite expensive. Also have Stellar Conquest, Thoneworld, and a few others.

I can highly recommend you take a look at Victory by Any Means (VBAM). The books are very well put together and a great value. The game system is looking very neat. They have a relatively active Discord channel too.

You by chance haven't ever played an old BBS game called Esterian Conquest have you?

**Comment by djberg96** [comment]
I have the latest VBAM, but haven't really looked at it yet. Pretty sure the rules for Imperium are out there somewhere, though I think there's a few different versions. I owned Stellar Conquest at one point and read the rules, but never got any takers. It's my understanding that it inspired the computer game _Master of Orion_. I also owned Throneworld at one point, even put together a solitaire scenario for it on BGG, but most people weren't interested.

Never heard of Esterian Conquest, sorry.

Ok, I've uploaded a PDF. Honestly, I never expected any visitors here. :)

**Comment by greenm01** [comment]
Hey, I started working on my own game. Please check it out. The specification is still in the early works. I would like to convert the Markdown to Latex when I'm finished. I've never used Latex in my life but I'm well aware of how useful it is:

https://github.com/greenm01/ec4x/blob/main/docs/ec4x_specs.md

Cheers!
